namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: iiparra/techtrends
  tag: 1.2.0 # Tagged from latest to version for production (standout exercise)
  pullPolicy: IfNotPresent

replicaCount: 1

resources: 
  requests: 
    memory: 64Mi
    cpu: 250m
  limits: 
    memory: 128Mi
    cpu: 500m
